"""Lemma 5 (load imbalance excess)

Generated by the Adaptive Agent Harness derivation kernel (strategy: balanced-allocation).
Exit-code contract: 0 = the proposition holds; 3 = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = 0
COUNTEREXAMPLE = 3


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {message}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {finding}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {reason}")
    raise SystemExit(4)


from sympy import expand
n1, n2 = symbols("n1 n2", integer=True, nonnegative=True)

lhs = 2 * (n1**2 + n2**2) - (n1 + n2) ** 2
if simplify(expand(lhs - (n1 - n2) ** 2)) == 0:
    hold("2*(n1^2+n2^2) - (n1+n2)^2 == (n1-n2)^2, a sum of squares")

k_hi, k_lo = symbols("k_hi k_lo", integer=True, positive=True)
before = k_hi**2 + k_lo**2
after = (k_hi - 1) ** 2 + (k_lo + 1) ** 2
if simplify(expand(before - after) - 2 * (k_hi - k_lo - 1)) == 0:
    hold("reassigning one task changes sum(n_j^2) by exactly 2*(k_hi - k_lo - 1)")
refute("the reassignment identity did not hold")
