"""Theorem 1 (first moment of a Pareto delay)

Generated by the Adaptive Agent Harness derivation kernel (strategy: power-law-moments).
Exit-code contract: 0 = the proposition holds; 3 = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = 0
COUNTEREXAMPLE = 3


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {message}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {finding}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {reason}")
    raise SystemExit(4)


a, m = symbols("a m", positive=True)
x = symbols("x", positive=True)
density = a * m**a / x**(a + 1)

E1 = integrate(x * density, (x, m, oo))
branch_value, branch_condition = E1.args[0]
print("E[X] =", branch_value, "admitted when", branch_condition)
if canon(branch_value - a * m / (a - 1)) == 0:
    hold(f"E[X] = a*m/(a-1), admitted exactly when {branch_condition}")
refute(f"E[X] evaluated to {branch_value}, which is not a*m/(a-1)")
