"""Theorem 2 (critical index and second moment)

Generated by the Adaptive Agent Harness derivation kernel (strategy: power-law-moments).
Exit-code contract: 0 = the proposition holds; 3 = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = 0
COUNTEREXAMPLE = 3


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {message}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {finding}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {reason}")
    raise SystemExit(4)


a, m = symbols("a m", positive=True)
x = symbols("x", positive=True)
density = a * m**a / x**(a + 1)

E2 = integrate(x**2 * density, (x, m, oo))
value, condition = E2.args[0]
print("E[X^2] =", value, "admitted when", condition)

# The critical index is where the improper integral stops converging: the
# variance must blow up as the index approaches 2 from above.
critical = simplify(limit(a * m**2 / ((a - 1) ** 2 * (a - 2)), a, 2, dir="+"))
if simplify(critical) == oo and str(condition) in {"a > 2", "a > 2.0"}:
    hold("E[X^2] = a*m^2/(a-2) for a>2, and Var(X) diverges as a -> 2 from above")
refute(f"critical-index behaviour was {critical} with condition {condition}")
