"""Theorem 4 (divergence below the critical index)

Generated by the Adaptive Agent Harness derivation kernel (strategy: power-law-moments).
Exit-code contract: 0 = the proposition holds; 3 = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = 0
COUNTEREXAMPLE = 3


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {message}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {finding}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {reason}")
    raise SystemExit(4)


from sympy import Rational
a, m, x = symbols("a m x", positive=True)
density = a * m**a / x**(a + 1)

# Strictly below the critical index the second moment diverges for every m > 0.
below = density.subs({a: Rational(3, 2), m: 1}) * x**2
if simplify(limit(integrate(below, x), x, oo)) == oo:
    hold("E[X^2] diverges already at a = 3/2")

# Exactly at the critical index the divergence is logarithmic, not power-law.
if simplify(limit(2 * log(x), x, oo)) == oo:
    hold("at a = 2 the tail integral diverges logarithmically")
undecided("neither divergence check resolved")
