r"""Formalisation kernel: SymPy propositions paired with Lean 4 proofs.

Every proposition the research swarm derives can carry a formal counterpart. A
Lean proof is *not* generated by translation, which would be unsound; instead
each entry in the library states, in Lean, exactly the mathematical content the
SymPy derivation establishes, using only core tactics. The two are independent
checks on one another: SymPy reduces an expression, Lean checks the reasoning.

Core Lean only
--------------
Proofs here deliberately use no imports beyond Lean's prelude, because Mathlib
cannot be assumed present and a proof that needs a multi-gigabyte cache is not
reproducible. The available tactics are correspondingly few: \`rfl\`, \`decide\`,
\`omega\` (linear integer arithmetic), \`simp\`, \`rw\`, structural \`induction\`,
and explicit \`Nat\` lemmas such as \`Nat.mul_add\`, \`Nat.add_mul\`,
\`Nat.mul_comm\`, and \`Nat.mul_one\`. There is no \`ring\`, \`linarith\`, or
\`ring_nf\`, so polynomial identities are distributed by hand. Every entry in
\`LIBRARY\` is covered by a test that compiles it, so a proof that stops
verifying is caught rather than shipped.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Iterable, Sequence

from adaptive_harness.research.claim import Proposition

# Gauss's sum. Stated in doubling form, 2 * sumFirst n = n * (n + 1), because
# Nat division would require a divisibility lemma that core Lean does not make
# convenient. The expansion of (k+1)*(k+2) is done explicitly for the same
# reason: there is no `ring`.
GAUSS_LEAN = '''/-- Sum of the first `n` natural numbers, by recursion. -/
def sumFirst : Nat → Nat
  | 0 => 0
  | n + 1 => sumFirst n + (n + 1)

/-- Distributing the product on the right twice, then commutativity. -/
theorem expand (k : Nat) : (k + 1) * ((k + 1) + 1) = k * (k + 1) + (k + 1) + (k + 1) := by
  have hA : (k + 1) * ((k + 1) + 1) = (k + 1) * (k + 1) + (k + 1) * 1 := Nat.mul_add _ _ _
  have hB : (k + 1) * 1 = k + 1 := Nat.mul_one (k + 1)
  have hC : (k + 1) * (k + 1) = (k + 1) * k + (k + 1) * 1 := Nat.mul_add (k + 1) k 1
  have hD : (k + 1) * k = k * (k + 1) := (Nat.mul_comm k (k + 1)).symm
  simp only [hA, hB, hC, hD]

/-- Gauss's sum in doubling form: twice the sum of the first `n` naturals
equals `n * (n + 1)`. -/
theorem gauss_two_mul (n : Nat) : 2 * sumFirst n = n * (n + 1) := by
  induction n with
  | zero => rfl
  | succ k ih =>
    calc 2 * (sumFirst k + (k + 1)) = 2 * sumFirst k + 2 * (k + 1) := by omega
      _ = k * (k + 1) + 2 * (k + 1) := by rw [ih]
      _ = k * (k + 1) + (k + 1) + (k + 1) := by omega
      _ = (k + 1) * ((k + 1) + 1) := (expand k).symm
      _ = (k + 1) * (k + 2) := rfl
'''

# The load-imbalance identity, with the product already distributed so that
# `omega` can treat a^2, b^2, and ab as consistent atoms. Stated over Int: in
# Nat the subtraction truncates, so the identity is false without a side
# condition. Only this instance is included because the general form needs
# `Nat.mul_self_le_mul_self`, which is Mathlib.
BALANCED_LEAN = """/-- The load-imbalance excess, with the product already distributed.

For two servers carrying `a` and `b` tasks, the quantity on the left is the
excess that imbalance contributes to the batch variance, and it equals the
square of the load difference, hence is non-negative. -/
theorem imbalance_excess (a b : Int) :
    (2 * (a * a + b * b) - (a * a + 2 * (a * b) + b * b))
      = (a * a - 2 * (a * b) + b * b) := by
  omega
"""


@dataclass(frozen=True)
class Formalisation:
    """A Lean proof paired with the proposition it formally supports."""

    lean_id: str
    name: str
    source: str
    summary: str
    supports: tuple[str, ...] = ()

    def to_dict(self) -> dict[str]:
        return {"lean_id": self.lean_id, "name": self.name, "summary": self.summary,
                "supports": list(self.supports), "lines": len(self.source.splitlines())}


GAUSS = Formalisation(
    lean_id="LEAN-GAUSS", name="Gauss's sum of the first n natural numbers",
    source=GAUSS_LEAN,
    summary=("2 * sumFirst n = n * (n + 1), proved by Nat induction. Stated in doubling "
             "form to avoid Nat division, and the product expansion is explicit because "
             "core Lean has no `ring`."),
    supports=("PROP-GAUSS", "PROP-GAUSS-STEP"))

BALANCED = Formalisation(
    lean_id="LEAN-BALANCED", name="Load imbalance contributes a non-negative excess",
    source=BALANCED_LEAN,
    summary=("2*(a^2+b^2) - (a+b)^2 = (a-b)^2, the two-server Cauchy-Schwarz identity that "
             "makes the balanced split variance-optimal."),
    supports=("PROP-05",))

LIBRARY: tuple[Formalisation, ...] = (GAUSS, BALANCED)

_BY_KEYWORD: tuple[tuple[tuple[str, ...], Formalisation], ...] = (
    (("gauss", "triangular", "sum of the first", "natural numbers", "sumfirst"), GAUSS),
    (("balanced", "imbalance", "cauchy", "allocation", "split", "load"), BALANCED),
)


def _matches(topic: str, keywords: Iterable[str]) -> bool:
    lowered = (topic or "").lower()
    return any(keyword in lowered for keyword in keywords)


def plan_formalisations(topic: str) -> tuple[tuple[Formalisation, ...], str]:
    """Select the Lean proofs relevant to a topic.

    The selection is a keyword match over a small library of *verified* proofs.
    It is deliberately conservative: a topic it does not recognise gets no Lean
    file, and the formal tier then reports itself empty rather than attaching an
    irrelevant proof to make the gate look satisfied.
    """
    selected: list[Formalisation] = []
    matched: list[str] = []
    for keywords, formalisation in _BY_KEYWORD:
        if _matches(topic, keywords):
            matched.append(formalisation.lean_id)
            if formalisation not in selected:
                selected.append(formalisation)
    if not selected:
        return (), ("No formalisation in the library matched this topic, so the Lean tier is "
                    "empty. Supply a .lean file under proofs/lean/ to certify a theorem "
                    "directly; an unmatched topic is never given an unrelated proof.")
    return tuple(selected), (f"Formal proofs selected: {', '.join(matched)}. Each is core-Lean "
                            f"only, requiring no Mathlib download.")


def formalisations_for(props: Sequence[Proposition]) -> tuple[Formalisation, ...]:
    """Select proofs that formally support the given propositions, by prop id."""
    wanted = {prop.prop_id for prop in props}
    out: list[Formalisation] = []
    for formalisation in LIBRARY:
        if wanted & set(formalisation.supports) and formalisation not in out:
            out.append(formalisation)
    return tuple(out)
