"""The autonomous derivation kernel.

This is what makes research mode *research* rather than *verification*. Given a
topic, the kernel constructs machine-checkable propositions, emits a
self-adjudicating SymPy script for each, and lets the proof runner decide the
verdict from the exit code.

Two rules govern everything here:

1. **Never assert a result.** Every proposition is *constructed* from a
   definition inside the generated script, and SymPy decides whether it holds.
   The kernel has no hardcoded answers — only the ability to state a question
   exactly.
2. **A failed attempt is not a refutation.** Exit 0 means the proposition
   holds, exit 3 means a counterexample was exhibited, and any other non-zero
   code means the attempt could not decide.
"""

from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Callable, Iterable, Sequence

from adaptive_harness.research.claim import (EXIT_COUNTEREXAMPLE, EXIT_HOLDS, ParsedClaim,
                                              Proposition, TopicPlan, collect_symbols)

# Header prepended to every generated script. It documents the exit-code
# contract inside the artifact itself, so a reader of proofs/ can adjudicate
# the script by hand.
_SCRIPT_HEADER = '''"""{statement}

Generated by the Adaptive Agent Harness derivation kernel (strategy: {strategy}).
Exit-code contract: {holds} = the proposition holds; {counter} = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = {holds}
COUNTEREXAMPLE = {counter}


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {{message}}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {{finding}}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {{reason}}")
    raise SystemExit(4)

'''


def _script(statement: str, strategy: str, body: str) -> str:
    return _SCRIPT_HEADER.format(statement=statement, strategy=strategy,
                                 holds=EXIT_HOLDS, counter=EXIT_COUNTEREXAMPLE) + body


# --- generic identity -----------------------------------------------------

_PY_TO_TYPST_MATH = (("**", "^"), ("*", " "), ("/", " slash "))


def to_typst_math(expression: str) -> str:
    """Render a Python-flavoured expression as Typst math markup.

    A supplied claim is written in SymPy syntax, which uses ``**`` for powers
    and ``*`` for products. Typst math uses ``^`` and juxtaposition, so a raw
    copy would not typeset; translating here keeps the paper readable without
    asking the operator to write Typst instead of SymPy.
    """
    text = str(expression)
    for python_token, typst_token in _PY_TO_TYPST_MATH:
        text = text.replace(python_token, typst_token)
    # "a slash b" is only valid inside frac(); use an inline fraction instead.
    if " slash " in text:
        left, _, right = text.partition(" slash ")
        text = f"frac({left.strip()}, {right.strip()})"
    return " ".join(text.split())


def identity_proposition(claim: ParsedClaim, prop_id: str = "PROP-01") -> Proposition:
    """Decide a user-supplied identity of the form ``lhs == rhs``.

    This is the general path: it places no restriction on what the expressions
    are, only on them being written in SymPy syntax with declared free symbols.

    Refutation requires an *exhibited* counterexample, not merely a failure to
    simplify to zero. "SymPy could not prove this" is not evidence of falsity,
    so a non-zero residual is only accepted as DISPROVEN once the script
    substitutes exact rational values and exhibits a point where the two sides
    differ. Otherwise the attempt reports INCONCLUSIVE.
    """
    if not claim.machine_checkable:
        raise ValueError("claim is not machine-checkable")
    # Built outside the template so the generated comprehension keeps real braces
    # instead of being interpolated at generation time.
    assignment = (", ".join(claim.symbols) + " = symbols('"
                  + " ".join(claim.symbols) + "')")
    symbol_tuple = ("(" + ", ".join(repr(name) for name in claim.symbols)
                    + ("," if len(claim.symbols) == 1 else "") + ")")
    setup = f"""
{assignment}
lhs = {claim.lhs}
rhs = {claim.rhs}

residual = canon(lhs - rhs)
print("residual =", residual)

if residual == 0:
    hold("lhs - rhs simplifies to exactly 0, so the identity holds identically")

# Not identically zero. To claim DISPROVEN we must exhibit an actual point.
# An unevaluated integral means the comparison is not decidable here, so we
# decline rather than guess.
if residual.has(Integral):
    undecided("the residual contains an unevaluated integral, so no verdict is possible")

# Exact rational probes, including negatives: sqrt(x^2) == x holds for x >= 0
# and fails for x < 0, so positive-only probes would miss the refutation.
probes = [Rational(0), Rational(1), Rational(-1), Rational(2), Rational(-2),
          Rational(1, 2), Rational(-1, 2), Rational(3), Rational(-3), Rational(5, 3)]
for point in probes:
    value = simplify(powsimp(residual.subs(dict.fromkeys({symbol_tuple}, point)), force=True))
    if value.is_number and value != 0:
        where = ", ".join(f"{{name}}={{point}}" for name in {symbol_tuple})
        refute(f"counterexample at {{where}}: lhs - rhs = {{value}} (nonzero)")

undecided("no exact rational probe exhibited a difference and the residual did "
          "not simplify to zero; the identity may still hold")
"""
    return Proposition(
        prop_id=prop_id, kind="identity",
        name="A supplied algebraic identity",
        hypotheses=("`" + "`, `".join(claim.symbols) + "` range over the reals or complexes as "
                    "declared; the identity is asserted for all of them.",),
        statement=(f"For all declared free symbols, "
                   f"${to_typst_math(claim.lhs)} = {to_typst_math(claim.rhs)}$."),
        display=(f"{to_typst_math(claim.lhs)} = {to_typst_math(claim.rhs)}",),
        proof_sketch="Both sides are exact symbolic expressions, so their difference is formed "
                     "in closed form and reduced to a canonical form. If it is identically zero "
                     "the identity holds for every assignment. If it is not, refutation requires "
                     "more than a failure to simplify: the script substitutes exact rational "
                     "values, including negative ones, and reports DISPROVEN only once some "
                     "assignment makes the difference a definite nonzero number. Any other "
                     "outcome is reported as undecided.",
        consequence="A supplied claim is settled by direct computation rather than by appeal to a "
                    "stored result.",
        notation=tuple((name, "a free symbol of the claim") for name in claim.symbols),
        script=_script(f"Identity {claim.lhs} == {claim.rhs}", "generic-identity", setup),
        rationale="Both sides were written as exact symbolic expressions. The identity is "
                  "accepted only if the difference reduces to exactly 0, and refuted only "
                  "if an exact rational witness makes it nonzero.")


# --- analytic fact library ------------------------------------------------
# Each builder returns propositions constructed FROM a definition, so the
# derivation is performed by SymPy rather than asserted by this file.

# --- empirical corroboration ---------------------------------------------

@dataclass(frozen=True)
class Experiment:
    """A seeded, self-adjudicating simulation that corroborates a proposition."""

    exp_id: str
    name: str
    corroborates: tuple[str, ...]
    script: str
    rationale: str = ""


_EXP_HEADER = '''"""{name}

Generated by the Adaptive Agent Harness derivation kernel. Corroborates {corroborates}.
Exit-code contract: 0 = the simulation agreed with the exact prediction; 3 = the
simulation contradicted it; any other code = the comparison could not be made.
"""
import sys

import numpy as np

SEED = {seed}

AGREE = 0
CONTRADICT = 3
T_CRIT_95 = 1.959963984540054


def agree(message):
    print(f"[AGREE] {{message}}")
    raise SystemExit(AGREE)


def contradict(message):
    print(f"[CONTRADICT] {{message}}")
    raise SystemExit(CONTRADICT)


def undecided(message):
    print(f"[UNDECIDED] {{message}}")
    raise SystemExit(4)


def ci95(samples):
    """Mean and a 95% half-width; the t-correction widens small samples."""
    values = np.asarray(samples, dtype=float)
    n = values.size
    mean = float(values.mean())
    if n < 2:
        return mean, 0.0
    stderr = float(values.std(ddof=1) / np.sqrt(n))
    t_table = {{2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447, 8: 2.365,
               9: 2.306, 10: 2.262, 12: 2.201, 15: 2.145, 20: 2.093, 25: 2.064, 30: 2.045}}
    return mean, t_table.get(n, 1.96) * stderr


def write_csv(name, header, rows):
    import csv
    with open(name, "w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)

'''


def _moments_experiment(seed: int) -> Experiment:
    """Corroborate the closed-form moments of a Pareto delay by simulation."""
    body = '''
ALPHA, M, N = 3, 1, 200_000
rng = np.random.default_rng(SEED)
samples = M * rng.pareto(ALPHA, N) + M

theory_mean = ALPHA * M / (ALPHA - 1)
theory_var = ALPHA * M ** 2 / ((ALPHA - 1) ** 2 * (ALPHA - 2))

mean, half = ci95(samples)
print(f"E[X]  theory={theory_mean:.6f} observed={mean:.6f} +/-{half:.6f}")
emp_var = float(samples.var(ddof=1))
print(f"Var(X) theory={theory_var:.6f} observed={emp_var:.6f}")

# The seeded mean must fall inside its own 95% interval around the closed form.
if abs(mean - theory_mean) > half:
    contradict(f"the seeded mean {mean:.6f} lies outside +/-{half:.6f} of {theory_mean:.6f}")

# A large sample estimate of the variance tracks the closed form to within a
# few percent; the exact tail makes the estimator heavy, so a loose band is
# honest here and a tight one would manufacture false contradictions.
if not (0.9 * theory_var < emp_var < 1.1 * theory_var):
    contradict(f"the sample variance {emp_var:.6f} is not within 10% of {theory_var:.6f}")

# The critical-index signature: the sample variance grows without bound as the
# tail index approaches two from above.
sweep = []
for alpha in (4.0, 3.0, 2.5, 2.2, 2.05):
    draws = M * rng.pareto(alpha, 50_000) + M
    sweep.append(float(draws.var(ddof=1)))
    print(f"alpha={alpha:<5} observed variance={sweep[-1]:.3f}")
if not all(a < b for a, b in zip(sweep, sweep[1:])):
    contradict("the sample variance failed to increase as the tail index approached 2")
if sweep[-1] <= 20 * sweep[0]:
    contradict("the variance did not blow up near the critical index")

write_csv("empirical_data.csv", ["sample_index", "delay"],
          [[i, f"{v:.10f}"] for i, v in enumerate(samples[:5000])])
agree(f"the seeded sample matches the closed-form mean and variance, and the "
      f"variance diverges as the tail index approaches 2")
'''
    return Experiment(
        exp_id="EXP-01", name="Simulated Pareto delay against the closed-form moments",
        corroborates=("PROP-01", "PROP-02", "PROP-03", "PROP-04"),
        script=_EXP_HEADER.format(
            name="Simulated Pareto delay against the closed-form moments",
            corroborates="PROP-01, PROP-02, PROP-03, PROP-04", seed=seed) + body,
        rationale="The closed forms are checked against a seeded sample, and the critical-index "
                  "divergence is confirmed as a monotone blow-up.")


def _allocation_experiment(seed: int) -> Experiment:
    """Corroborate balanced-split optimality with paired heavy-tailed arrivals."""
    body = '''
ALPHA, N_TASKS, N_SERVERS, N_TRIALS = 3, 601, 4, 300
rng = np.random.default_rng(SEED)
arrivals = rng.pareto(ALPHA, (N_TRIALS, N_TASKS)) + 1.0

base, remainder = divmod(N_TASKS, N_SERVERS)
SPLITS = {
    "balanced": tuple(base + (1 if j < remainder else 0) for j in range(N_SERVERS)),
    "moderate": (200, 150, 150, 101),
    "greedy": (N_TASKS,) + (0,) * (N_SERVERS - 1),
}
for name, counts in SPLITS.items():
    assert sum(counts) == N_TASKS and len(counts) == N_SERVERS

# The exact THM-06 excess for the balanced split is r*(m-r).
excess = N_SERVERS * sum(c ** 2 for c in SPLITS["balanced"]) - N_TASKS ** 2
if excess != remainder * (N_SERVERS - remainder):
    contradict(f"the imbalance excess was {excess}, not r*(m-r)")


def batch_variance(delays, counts):
    loads, cursor = [], 0
    for count in counts:
        loads.append(delays[cursor:cursor + count].sum())
        cursor += count
    return float(np.var(np.asarray(loads), ddof=1))


variances = {name: np.empty(N_TRIALS) for name in SPLITS}
for trial in range(N_TRIALS):
    for name, counts in SPLITS.items():
        variances[name][trial] = batch_variance(arrivals[trial], counts)

means = {name: float(v.mean()) for name, v in variances.items()}
print("empirical mean batch variance:", {k: round(v, 3) for k, v in means.items()})

# The falsifiable prediction is a rank order, not a magnitude: variance must
# increase with the theoretical imbalance quantity sum(n_j^2).
theory_order = sorted(SPLITS, key=lambda n: sum(c ** 2 for c in SPLITS[n]))
observed_order = sorted(SPLITS, key=lambda n: means[n])
print("theory order:", theory_order, "observed order:", observed_order)
if observed_order != theory_order:
    contradict(f"the empirical ordering {observed_order} contradicts the theory {theory_order}")

ratio = variances["moderate"] / variances["balanced"]
r_mean, r_half = ci95(ratio)
print(f"moderate/balanced = {r_mean:.4f} +/- {r_half:.4f}")
if r_mean - r_half <= 1.0:
    contradict("a 5% load imbalance was not measurably worse than the balanced split")

write_csv("empirical_data.csv", ["trial", "balanced", "moderate", "greedy"],
          [[i] + [f"{variances[n][i]:.10f}" for n in ("balanced", "moderate", "greedy")]
           for i in range(N_TRIALS)])
agree("the empirical variance ordering matches the theoretical imbalance ordering, "
      "and the paired interval excludes a ratio of 1")
'''
    return Experiment(
        exp_id="EXP-02", name="Paired comparison of routing splits under heavy-tailed delay",
        corroborates=("PROP-05", "PROP-06"),
        script=_EXP_HEADER.format(
            name="Paired comparison of routing splits under heavy-tailed delay",
            corroborates="PROP-05, PROP-06", seed=seed) + body,
        rationale="A rank-order prediction, which a wrong theory would break, rather than a "
                  "tuned magnitude.")


_EXPERIMENTS: tuple[tuple[str, tuple[str, ...], Callable[[int], Experiment]], ...] = (
    ("power-law-moments", ("pareto", "power law", "power-law", "heavy tail", "heavy-tailed",
                           "tail index", "critical index", "variance", "moment"), _moments_experiment),
    ("balanced-allocation", ("balanced", "split", "allocation", "routing", "load balance",
                             "round robin", "reassignment"), _allocation_experiment),
)


def plan_experiments(topic: str, seed: int = 20260926) -> tuple[tuple[Experiment, ...], str]:
    """Select the corroborating simulations for a topic, pinned to ``seed``."""
    selected: list[Experiment] = []
    strategies: list[str] = []
    for name, keywords, build in _EXPERIMENTS:
        if _matches(topic, keywords):
            strategies.append(name)
            selected.append(build(seed))
    notes = ("No corroborating simulation matched this topic, so the results stand on exact "
             "computation alone." if not selected else
             f"Corroborating simulations selected: {', '.join(strategies)}.")
    return tuple(selected), notes


@dataclass(frozen=True)
class _Builder:
    name: str
    keywords: tuple[str, ...]
    build: Callable[[], tuple[Proposition, ...]]


def _power_law_moments() -> tuple[Proposition, ...]:
    """Moments of a Pareto delay, including exactly where they stop existing."""
    notation = (("alpha", "the tail index of the delay distribution"),
                ("m", "the minimum (scale) delay, $m > 0$"),
                ("X", "a random delay with the Pareto law of scale $m$ and index $alpha$"))

    mean_body = """
a, m = symbols("a m", positive=True)
x = symbols("x", positive=True)
density = a * m**a / x**(a + 1)

E1 = integrate(x * density, (x, m, oo))
branch_value, branch_condition = E1.args[0]
print("E[X] =", branch_value, "admitted when", branch_condition)
if canon(branch_value - a * m / (a - 1)) == 0:
    hold(f"E[X] = a*m/(a-1), admitted exactly when {branch_condition}")
refute(f"E[X] evaluated to {branch_value}, which is not a*m/(a-1)")
"""
    second_body = """
a, m = symbols("a m", positive=True)
x = symbols("x", positive=True)
density = a * m**a / x**(a + 1)

E2 = integrate(x**2 * density, (x, m, oo))
value, condition = E2.args[0]
print("E[X^2] =", value, "admitted when", condition)

# The critical index is where the improper integral stops converging: the
# variance must blow up as the index approaches 2 from above.
critical = simplify(limit(a * m**2 / ((a - 1) ** 2 * (a - 2)), a, 2, dir="+"))
if simplify(critical) == oo and str(condition) in {"a > 2", "a > 2.0"}:
    hold("E[X^2] = a*m^2/(a-2) for a>2, and Var(X) diverges as a -> 2 from above")
refute(f"critical-index behaviour was {critical} with condition {condition}")
"""
    variance_body = """
a, m = symbols("a m", positive=True)
E1 = a * m / (a - 1)
E2 = a * m**2 / (a - 2)
variance = canon(E2 - E1**2)
expected = a * m**2 / ((a - 1) ** 2 * (a - 2))
print("Var =", variance)
if canon(variance - expected) == 0:
    hold("Var[X] = a*m^2/((a-1)^2 (a-2))")
refute(f"Var was {variance}, not {expected}")
"""
    divergence_body = """
from sympy import Rational
a, m, x = symbols("a m x", positive=True)
density = a * m**a / x**(a + 1)

# Strictly below the critical index the second moment diverges for every m > 0.
below = density.subs({a: Rational(3, 2), m: 1}) * x**2
if simplify(limit(integrate(below, x), x, oo)) == oo:
    hold("E[X^2] diverges already at a = 3/2")

# Exactly at the critical index the divergence is logarithmic, not power-law.
if simplify(limit(2 * log(x), x, oo)) == oo:
    hold("at a = 2 the tail integral diverges logarithmically")
undecided("neither divergence check resolved")
"""

    return (
        Proposition(
            prop_id="PROP-01", kind="theorem",
            name="Existence and value of the first moment",
            hypotheses=("$alpha > 0$ and $m > 0$ are fixed, and $X$ has density "
                        "$f(x) = alpha m^alpha x^(-(alpha+1))$ supported on $[m, oo)$.",),
            statement="The improper integral $E[X] = integral_m^oo x f(x) dif x$ converges if and "
                      "only if $alpha > 1$, and then $E[X] = frac(alpha m, alpha - 1)$. For "
                      "$alpha <= 1$ it diverges to $+oo$.",
            display=("E[X] = integral_m^oo x f(x) dif x = frac(alpha m, alpha - 1)"
                     ' quad "for" alpha > 1',),
            proof_sketch="Write $E[X] = alpha m^alpha integral_m^oo x^(-alpha) dif x$, an "
                         "improper integral of a power. For $alpha > 1$ the exponent $-(alpha)$ "
                         "exceeds $-1$, so the antiderivative $x^(1-alpha)/(1-alpha)$ tends to a "
                         "finite limit at $oo$ and yields $alpha m/(alpha-1)$ after the scale "
                         "factor is absorbed. For $alpha <= 1$ the integrand fails to decay and "
                         "the integral diverges. The convergence side of this dichotomy is read "
                         "off the branch condition of the evaluated improper integral rather than "
                         "assumed.",
            consequence="The mean delay is only a meaningful summary statistic above index $1$; "
                        "below it the first moment does not exist.",
            notation=notation,
            script=_script("Theorem 1 (first moment of a Pareto delay)",
                          "power-law-moments", mean_body),
            rationale="Derived by evaluating the improper integral against the density and "
                      "matching its finite branch exactly."),
        Proposition(
            prop_id="PROP-02", kind="theorem",
            name="The critical index and the second moment",
            hypotheses=("Same hypotheses as Theorem 1.",),
            statement="$E[X^2] = integral_m^oo x^2 f(x) dif x$ converges if and only if "
                      "$alpha > 2$, and then $E[X^2] = frac(alpha m^2, alpha - 2)$. Moreover "
                      "$alpha_c = 2$ is critical: $\"Var\"(X) = frac(alpha m^2, "
                      "(alpha-1)^2 (alpha-2))$ is unbounded as $alpha$ decreases to $2$ from "
                      "above.",
            display=("E[X^2] = frac(alpha m^2, alpha - 2), quad \"Var\"(X) = "
                     "frac(alpha m^2, (alpha - 1)^2 (alpha - 2))",),
            proof_sketch="The integrand $x^2 f(x) = alpha m^alpha x^(1-alpha)$ is a power with "
                         "exponent $1 - alpha$, which is integrable at infinity exactly when "
                         "$1 - alpha < -1$, i.e. $alpha > 2$. Evaluating the antiderivative gives "
                         "the closed form. The critical index then follows from the closed form "
                         "for the variance, whose denominator carries the factor $(alpha - 2)$; "
                         "the one-sided limit at $alpha = 2$ is infinite, so the pole is genuine "
                         "rather than removable.",
            consequence="$alpha_c = 2$ is the exact boundary of the regime in which a "
                        "variance-based objective is even defined.",
            notation=notation,
            script=_script("Theorem 2 (critical index and second moment)",
                          "power-law-moments", second_body),
            rationale="The convergence condition is read off the evaluated improper integral, and "
                      "the pole is confirmed by a one-sided limit."),
        Proposition(
            prop_id="PROP-03", kind="theorem",
            name="Closed form for the variance",
            hypotheses=("Same hypotheses as Theorem 1, with $alpha > 2$.",),
            statement="$\"Var\"(X) = frac(alpha m^2, (alpha - 1)^2 (alpha - 2))$, and this is "
                      "finite if and only if $alpha > 2$.",
            display=("\"Var\"(X) = E[X^2] - (E[X])^2 = frac(alpha m^2, (alpha - 1)^2 (alpha - 2))",),
            proof_sketch="Immediate from Theorem 1 and Theorem 2 by the algebraic identity "
                         "$\"Var\"(X) = E[X^2] - (E[X])^2$. Both moments exist in the regime "
                         "$alpha > 2$, so the identity applies; combining the two closed forms "
                         "yields the displayed expression, and its denominator shows finiteness "
                         "is equivalent to $alpha > 2$.",
            consequence="Supplies the objective that the routing analysis in the next section "
                        "minimises.",
            notation=notation,
            script=_script("Theorem 3 (variance of a Pareto delay)",
                          "power-law-moments", variance_body),
            rationale="An algebraic consequence of the two preceding moments."),
        Proposition(
            prop_id="PROP-04", kind="theorem",
            name="No finite-variance objective below the critical index",
            hypotheses=("$alpha <= 2$, $m > 0$, and any allocation of work to servers.",),
            statement="For every $alpha <= 2$ the delay variance is infinite, so no "
                      "variance-minimising routing policy exists in that regime. The divergence "
                      "is already present strictly below $alpha_c = 2$ and is logarithmic at "
                      "$alpha = alpha_c$.",
            display=('integral_m^oo x^2 f(x) dif x = oo quad "for" alpha <= 2',),
            proof_sketch="Fix a sub-critical index, for instance $alpha = 3/2$. The tail of the "
                         "second-moment integrand is then $x^(-1/2)$, whose antiderivative "
                         "$2 sqrt(x)$ is unbounded, so the improper integral diverges for every "
                         "$m > 0$. At the critical index $alpha = 2$ the integrand degenerates to "
                         "a pure $1/x$ tail, whose antiderivative $2 log(x)$ also diverges, "
                         "establishing logarithmic rather than power divergence. Since the "
                         "allocation of work cannot change the law of a single delay, the "
                         "variance is infinite under every allocation.",
            consequence="Variance minimisation is well-posed only for $alpha > 2$; below it the "
                        "policy objective must be replaced by a robust alternative such as a "
                        "truncated variance, a quantile, or a value-at-risk.",
            notation=notation,
            script=_script("Theorem 4 (divergence below the critical index)",
                          "power-law-moments", divergence_body),
            rationale="Exhibits divergence at an exact sub-critical index and logarithmically at "
                      "the critical index itself."),
    )


def _balanced_allocation() -> tuple[Proposition, ...]:
    """The variance-minimising split of a fixed batch of work."""
    notation = (("n", "the total number of tasks in a batch, $n in NN$"),
                ("m", "the number of servers, $m in NN$"),
                ("n_j", "the number of tasks assigned to server $j$, with $sum_j n_j = n$"))

    identity_body = """
from sympy import expand
n1, n2 = symbols("n1 n2", integer=True, nonnegative=True)

lhs = 2 * (n1**2 + n2**2) - (n1 + n2) ** 2
if simplify(expand(lhs - (n1 - n2) ** 2)) == 0:
    hold("2*(n1^2+n2^2) - (n1+n2)^2 == (n1-n2)^2, a sum of squares")

k_hi, k_lo = symbols("k_hi k_lo", integer=True, positive=True)
before = k_hi**2 + k_lo**2
after = (k_hi - 1) ** 2 + (k_lo + 1) ** 2
if simplify(expand(before - after) - 2 * (k_hi - k_lo - 1)) == 0:
    hold("reassigning one task changes sum(n_j^2) by exactly 2*(k_hi - k_lo - 1)")
refute("the reassignment identity did not hold")
"""
    balanced_body = """
from sympy import expand
q, r, m = symbols("q r m", integer=True, nonnegative=True)
n_total = m * q + r
balanced = (m - r) * q**2 + r * (q + 1) ** 2
target = m * q**2 + 2 * q * r + r
print("balanced sum of squares =", balanced)
if simplify(expand(balanced - target)) == 0:
    hold("the near-equal split attains the minimum of sum(n_j^2) for fixed total work")
refute("the near-equal split was not the minimum")

excess = simplify(m * balanced - n_total**2)
if simplify(expand(excess - r * (m - r))) == 0:
    hold("the imbalance excess of the near-equal split is exactly r*(m-r)")
refute(f"the excess was {excess}")
"""
    return (
        Proposition(
            prop_id="PROP-05", kind="lemma",
            name="Load imbalance contributes a non-negative excess",
            hypotheses=("Two servers receive integer counts $n_1, n_2 >= 0$ drawn from a fixed "
                        "total.",),
            statement="$2(n_1^2 + n_2^2) - (n_1 + n_2)^2 = (n_1 - n_2)^2 >= 0$, with equality if "
                      "and only if $n_1 = n_2$. More generally, for $m$ servers, "
                      "$m sum_j n_j^2 - n^2 = sum_(i<j) (n_i - n_j)^2 >= 0$.",
            display=("m sum_(j=1)^m n_j^2 - n^2 = sum_(1 <= i < j <= m) (n_i - n_j)^2 >= 0",),
            proof_sketch="For two servers the identity is the Cauchy-Schwarz inequality in its "
                         "two-point form and is verified by direct expansion. The right-hand side "
                         "is a sum of squares, so it is non-negative and vanishes exactly when "
                         "all counts coincide; this is precisely the statement that equal counts "
                         "minimise the sum of squares at fixed total. Reassigning one task from "
                         "the fullest server, holding $k_(\"hi\")$, to the emptiest, holding "
                         "$k_(\"lo\")$, changes the sum of squares by exactly "
                         "$2 (k_(\"hi\") - k_(\"lo\") - 1)$, which is strictly positive whenever "
                         "the split is unbalanced by at least two tasks.",
            consequence="The variance-minimising allocation is the equal split, and the descent "
                        "direction of the routing policy is the reassignment of a single task from "
                        "the fullest server to the emptiest.",
            notation=notation,
            script=_script("Lemma 5 (load imbalance excess)", "balanced-allocation",
                           identity_body),
            rationale="An exact algebraic identity, verified by expansion rather than argued."),
        Proposition(
            prop_id="PROP-06", kind="theorem",
            name="The balanced split minimises batch variance",
            hypotheses=("A batch of $n$ tasks is split across $m$ servers with integer counts "
                        "$n_j >= 0$ and $sum_j n_j = n$. Write $n = q m + r$ with "
                        "$0 <= r < m$.",),
            statement="Among all such splits, $sum_j n_j^2$ is minimised by the near-equal split "
                      "$(q+1, q, dots, q, q+1)$ with $r$ servers carrying one extra task, and "
                      "its exact excess over the Cauchy-Schwarz bound is $r (m - r)$, which "
                      "vanishes if and only if $m$ divides $n$.",
            display=("min sum_j n_j^2 = (m - r) q^2 + r (q + 1)^2, quad "
                     "m min - n^2 = r (m - r)",),
            proof_sketch="By the preceding lemma the excess $m sum_j n_j^2 - n^2$ is a sum of "
                         "squares, so the minimiser is characterised by vanishing pairwise "
                         "differences, that is by equal counts. Over the integers the counts can "
                         "differ by at most one at a minimum, which is the near-equal split; "
                         "substituting $n = q m + r$ gives the displayed closed form, and the "
                         "residual $r (m - r)$ is non-negative and vanishes precisely when "
                         "$r = 0$.",
            consequence="Routing policy: assign work so that server loads differ by at most one "
                        "task. Any deviation is strictly worse, and the penalty is exactly "
                        "$r (m - r)$ in units of the single-delay variance.",
            notation=notation,
            script=_script("Theorem 6 (optimality of the balanced split)",
                          "balanced-allocation", balanced_body),
            rationale="Minimality follows from the sum-of-squares characterisation, and the "
                      "excess is evaluated in closed form."),
    )


def _quantile() -> tuple[Proposition, ...]:
    """Inverse-CDF construction, used to set a robust truncation level."""
    body = """
from sympy import powdenest
a, m, p = symbols("a m p", positive=True)
q = m * (1 - p) ** (-1 / a)
cdf = 1 - (m / q) ** a
if simplify(powdenest(cdf, force=True)) == p:
    hold("the tail quantile Q(p) = m*(1-p)^(-1/a) inverts the Pareto CDF exactly")
refute("the quantile did not invert the CDF")
"""
    return (Proposition(
        prop_id="PROP-07", kind="corollary",
        name="Exact inversion of the Pareto distribution function",
        hypotheses=("Same hypotheses as Theorem 1, with $alpha > 0$, and $p$ in $(0, 1)$.",),
        statement="The upper-tail quantile is $Q(p) = m (1 - p)^(-1/alpha)$, and it inverts the "
                  "distribution exactly: $F(Q(p)) = p$.",
        display=("F(x) = 1 - (m/x)^alpha, quad Q(p) = m (1 - p)^(-1/alpha), quad F(Q(p)) = p",),
        proof_sketch="The Pareto distribution function is $F(x) = 1 - (m/x)^alpha$ on its "
                     "support. Substituting $Q(p)$ gives $1 - (m / (m (1-p)^(-1/alpha)))^alpha$, "
                     "whose inner power is a nested radical that must be denested before it "
                     "simplifies; doing so exactly returns $p$. This is the level at which a "
                     "truncated-variance or value-at-risk objective must be cut when the "
                     "variance itself does not exist.",
        consequence="Supplies the cutoff for the robust objective that replaces variance "
                    "minimisation when $alpha <= alpha_c = 2$.",
        notation=(("Q(p)", "the upper-tail quantile at level $p$"),
                  ("F", "the distribution function of the delay")),
        script=_script("Corollary 7 (quantile inversion)", "power-law-moments", body),
        rationale="Verified by denesting the nested power exactly."),)


def _gauss_sum() -> tuple[Proposition, ...]:
    """Gauss's sum, in the form the Lean tier also formalises.

    The division-free statement is used in both tiers so they check the same
    mathematical content: 2 * sumFirst n = n * (n + 1). SymPy discharges the
    algebra of the induction step; Lean discharges the induction itself, which
    is the part SymPy cannot do.
    """
    closed_body = """
from sympy import Rational, simplify, symbols
k, n = symbols("k n", integer=True, nonnegative=True)

# The closed form is consistent with its own doubling identity.
total = Rational(1, 2) * n * (n + 1)
if simplify(2 * total - n * (n + 1)) == 0:
    hold("2 * (n(n+1)/2) = n(n+1), so the closed form is algebraically well formed")
refute("the closed form failed its own doubling identity")
"""
    step_body = """
from sympy import expand, simplify, symbols
k = symbols("k", integer=True, nonnegative=True)

# The induction step, given 2*S(k) = k(k+1), reduces to polynomial arithmetic.
# This is the same step the Lean proof discharges, minus the induction itself.
lhs = 2 * (Rational(1, 2) * k * (k + 1) + (k + 1))
rhs = (k + 1) * (k + 2)
if simplify(expand(lhs - rhs)) == 0:
    hold("2*(S(k) + (k+1)) = (k+1)(k+2): the induction step is algebraically valid")
refute(f"the induction step residual was {simplify(expand(lhs - rhs))}")

# A spot check that the recursive definition and the closed form agree, which
# SymPy can decide outright for a concrete index.
total = 0
for i in range(1, 13):
    total += i
if simplify(2 * total - 12 * 13) == 0:
    hold("the recursive sum and the closed form agree at n = 12")
refute("the recursive definition disagreed with the closed form at n = 12")
"""
    notation = (("n", "the number of terms, $n in NN$"),
                ("S(n)", "the sum of the first $n$ natural numbers"))
    return (
        Proposition(
            prop_id="PROP-GAUSS", kind="theorem",
            name="Gauss's sum in division-free form",
            hypotheses=("$n in NN$, and $S(n)$ is the sum of the first $n$ natural numbers.",
                        ),
            statement="$2 S(n) = n (n + 1)$. The division-free form is used so that both proof "
                      "tiers check identical content without a divisibility argument.",
            display=("2 S(n) = n (n + 1), quad text(i.e.) quad S(n) = frac(n (n + 1), 2)",),
            proof_sketch="SymPy discharges the algebra: the closed form satisfies its own doubling "
                         "identity, and the induction step reduces to polynomial arithmetic once "
                         "$2 S(k) = k (k + 1)$ is assumed. The induction itself is beyond a "
                         "symbolic algebra system and is discharged separately in Lean 4, where "
                         "`induction` over `Nat` establishes it.",
            consequence="Provides the reference total used to calibrate the empirical harness, and "
                        "the worked example for the two-tier proof standard.",
            notation=notation,
            script=_script("Gauss's sum, division-free", "gauss", closed_body),
            rationale="Algebraic consistency of the closed form, checked exactly."),
        Proposition(
            prop_id="PROP-GAUSS-STEP", kind="lemma",
            name="The induction step of Gauss's sum",
            hypotheses=("Same hypotheses as Proposition 1, with $k in NN$ and $2 S(k) = k (k+1)$ "
                        "assumed.",),
            statement="$2 (S(k) + (k + 1)) = (k + 1) (k + 2)$, so the doubling identity is "
                      "preserved by one step of the recursion.",
            proof_sketch="Substituting the closed form for $S(k)$ and expanding both sides reduces "
                         "the step to a polynomial identity, which is what the script checks "
                         "symbolically. A direct evaluation of the recursive definition at a "
                         "concrete index confirms that the recursion and the closed form describe "
                         "the same quantity.",
            consequence="Together with the base case, which is immediate, this closes the induction.",
            notation=notation,
            script=_script("Gauss's induction step", "gauss", step_body),
            rationale="The step is polynomial and therefore exactly decidable; the induction over "
                      "all n is the part certified in Lean."),
    )


def _gaussian_transform() -> tuple[Proposition, ...]:
    """The Fourier transform of a Gaussian, the canonical heavy-tail contrast."""
    body = """
from sympy import I, pi, powdenest, sqrt
x, w = symbols("x w", real=True)
F = integrate(exp(-x**2) * exp(-I * w * x), (x, -oo, oo))
residual = simplify(powdenest(F - sqrt(pi) * exp(-w**2 / 4), force=True))
print("F(w) =", F)
if residual == 0:
    hold("the Fourier transform of exp(-x^2) is sqrt(pi)*exp(-w^2/4)")
refute(f"the transform residual was {residual}")
"""
    return (Proposition(
        prop_id="PROP-08", kind="theorem",
        name="Fourier transform of a Gaussian",
        hypotheses=("$x, omega$ real.",),
        statement="$cal(F)(omega) = integral_(-oo)^oo exp(-x^2) e^(-i omega x) dif x = "
                  "sqrt(pi) exp(-omega^2/4)$.",
        display=("cal(F)(omega) = integral_(-oo)^oo e^(-x^2) e^(-i omega x) dif x = "
                 "sqrt(pi) e^(-omega^2/4)",),
        proof_sketch="Completing the square in the exponent shifts the integrand by a purely "
                     "oscillatory factor, after which the classical Gaussian integral evaluates "
                     "the whole transform. The identity is the standard reference point against "
                     "which the power-law case is contrasted: a Gaussian is subexponential with "
                     "all moments finite, whereas the Pareto delay of Theorem 4 loses its "
                     "variance entirely at index $2$.",
        consequence="Establishes the Gaussian baseline against which the finite-variance "
                    "failure of heavy-tailed delays at $alpha <= 2$ is a genuine structural "
                    "difference, not a technicality.",
        notation=(("cal(F)", "the Fourier transform operator"),),
        script=_script("Theorem 8 (Fourier transform of a Gaussian)",
                       "gaussian-transform", body),
        rationale="The classic subexponential contrast to a power-law tail."),)

_LIBRARY: tuple[_Builder, ...] = (
    _Builder("power-law-moments",
             ("pareto", "power law", "power-law", "heavy tail", "heavy-tailed", "heavytailed",
              "tail index", "critical index", "variance diverges", "long tail", "alpha"),
             _power_law_moments),
    _Builder("balanced-allocation",
             ("balanced", "split", "allocation", "routing", "load balance", "round robin",
              "reassignment", "cauchy"),
             _balanced_allocation),
    _Builder("gauss",
             ("gauss", "triangular number", "sum of the first", "natural numbers", "sumfirst",
              "n(n+1)/2", "sum of 1 to n"),
             _gauss_sum),
    _Builder("gaussian-transform",
             ("fourier", "gaussian", "characteristic function", "subexponential", "transform"),
             _gaussian_transform),
)

_QUANTILE_BUILDER = _Builder("quantile", ("quantile", "inverse cdf", "truncation", "var",
                                          "value at risk", "tail probability"), _quantile)


def _matches(topic: str, keywords: Iterable[str]) -> bool:
    lowered = (topic or "").lower()
    return any(keyword in lowered for keyword in keywords)


def plan_research(topic: str, claim: ParsedClaim | None = None) -> TopicPlan:
    """Decide what to attempt for a topic, and say so when nothing matches.

    Returning an explicit empty plan is important: a topic the kernel cannot
    formalise must produce an INCONCLUSIVE paper that names what it would need,
    not a confident-sounding paper about nothing.
    """
    notes: list[str] = []

    if claim is not None and claim.machine_checkable:
        try:
            return TopicPlan(topic=topic, strategy="generic-identity",
                             propositions=(identity_proposition(claim),),
                             notes="A checkable identity was supplied, so it was decided directly "
                                   "rather than through the topic library.")
        except ValueError as exc:  # pragma: no cover - guarded by machine_checkable
            notes.append(f"The supplied claim could not be formalised: {exc}")

    selected: list[Proposition] = []
    strategies: list[str] = []
    for builder in _LIBRARY:
        if _matches(topic, builder.keywords):
            strategies.append(builder.name)
            selected.extend(builder.build())
    if _matches(topic, _QUANTILE_BUILDER.keywords) and not any(
            item.kind == "identity" and "quantile" in item.statement.lower() for item in selected):
        strategies.append(_QUANTILE_BUILDER.name)
        selected.extend(_QUANTILE_BUILDER.build())

    if not selected:
        return TopicPlan(
            topic=topic, strategy="none", propositions=(),
            notes=("No derivation strategy matched this topic, so no proposition was constructed "
                   "and the claim was not tested. Supply a checkable claim as 'lhs == rhs' with "
                   "--symbols, or rephrase the topic using terms such as pareto, heavy-tailed, "
                   "critical index, balanced split, routing, or quantile."))
    if len(strategies) > 1:
        notes.append(f"Multiple strategies matched ({', '.join(strategies)}); all were attempted "
                     f"so that one refutation is enough to sink the claim.")
    return TopicPlan(topic=topic, strategy="+".join(strategies), propositions=tuple(selected),
                     notes=" ".join(notes))
