"""Gauss's induction step

Generated by the Adaptive Agent Harness derivation kernel (strategy: gauss).
Exit-code contract: 0 = the proposition holds; 3 = a counterexample
was exhibited; any other code = the attempt could not decide.
"""
import sys

# A user-supplied expression may name any SymPy object, so the whole namespace
# is imported rather than a hand-maintained list that would go stale.
from sympy import *
from sympy import powsimp, simplify

HOLD = 0
COUNTEREXAMPLE = 3


def canon(expr):
    """Canonicalize an exact expression before comparing it."""
    return simplify(powsimp(expr, force=True))


def hold(message):
    print(f"[HOLD] {message}")
    raise SystemExit(HOLD)


def refute(finding):
    print(f"[COUNTEREXAMPLE] {finding}")
    raise SystemExit(COUNTEREXAMPLE)


def undecided(reason):
    print(f"[UNDECIDED] {reason}")
    raise SystemExit(4)


from sympy import expand, simplify, symbols
k = symbols("k", integer=True, nonnegative=True)

# The induction step, given 2*S(k) = k(k+1), reduces to polynomial arithmetic.
# This is the same step the Lean proof discharges, minus the induction itself.
lhs = 2 * (Rational(1, 2) * k * (k + 1) + (k + 1))
rhs = (k + 1) * (k + 2)
if simplify(expand(lhs - rhs)) == 0:
    hold("2*(S(k) + (k+1)) = (k+1)(k+2): the induction step is algebraically valid")
refute(f"the induction step residual was {simplify(expand(lhs - rhs))}")

# A spot check that the recursive definition and the closed form agree, which
# SymPy can decide outright for a concrete index.
total = 0
for i in range(1, 13):
    total += i
if simplify(2 * total - 12 * 13) == 0:
    hold("the recursive sum and the closed form agree at n = 12")
refute("the recursive definition disagreed with the closed form at n = 12")
